global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules'

scrape_configs:
  - job_name: dummy
    consul_sd_configs:
      - server: 'localhost:8500'
    relabel_configs:
      - source_labels: ['__meta_consul_address']
        target_label: __address__
        regex: (.*)
        replacement: $1:9126
  - job_name: verenmq
    consul_sd_configs:
      - server: 'localhost:8500'
        services: ['vernemq']
    relabel_configs:
      - source_labels: ['__meta_consul_address']
        target_label: __address__
        regex: (.*)
        replacement: $1:8888
  - job_name: consul
    static_configs:
      - targets: ['localhost:9107']
