---
# The order here matters
- name: restart telegraf
  service:
    name: telegraf
    state: restarted
  become: true
  when: telegraf_start_service

- name: pause
  pause:
    seconds: "{{ telegraf_start_delay }}"
  when: telegraf_start_service
