---
#- name: Retrieve ec2 facts
#  ec2_metadata_facts:
#  when: telegraf_aws_tags

#- name: Retrieve all ec2 tags on the instance
#  ec2_tag:
#    region: "{{ ansible_ec2_placement_region }}"
#    resource: "{{ ansible_ec2_instance_id }}"
#    state: list
#  when: telegraf_aws_tags
#  register: ec2_tags

- name: Set templatized Telegraf configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ telegraf_configuration_dir }}/{{ item.dest }}"
    force: yes
    backup: yes
    owner: telegraf
    group: telegraf
    mode: 0744
  with_items:
    - { src: 'telegraf.d/filebeat.conf.j2', dest: 'telegraf.d/filebeat.conf' }
    - { src: 'telegraf.conf.j2', dest: 'telegraf.conf' }
  when: telegraf_template_configuration
  # If config changes, restart telegraf and confirm it remained running
  notify:
    - "restart telegraf"
    - "pause"
